collections:
  portfolio:
    output: true
    permalink: /:collection/:name:output_ext
  code:
    output: true
    permalink: /:collection/:name:output_ext
  concepts:
    output: true
    permalink: /:collection/:name:output_ext